# Generated by Django 4.2.2 on 2023-09-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='computer',
            new_name='photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='investment',
        ),
    ]
