# Generated by Django 4.2.2 on 2023-09-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_computer_photo_photos_remove_photo_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
