# Generated by Django 4.2.2 on 2023-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_user_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(default='None', upload_to='textile')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(default=None, max_length=50)),
                ('mainprice', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('realprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(default='None', upload_to='textile')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(default=None, max_length=50)),
                ('size', models.CharField(max_length=2)),
                ('size1', models.CharField(max_length=2)),
                ('size2', models.CharField(max_length=2)),
                ('size3', models.CharField(max_length=2)),
                ('mainprice', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('realprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(default='None', upload_to='textile')),
                ('name', models.CharField(max_length=50)),
                ('kg', models.CharField(default=None, max_length=10)),
                ('mainprice', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('realprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
