# Generated by Django 4.2.2 on 2023-11-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_jewellery_created_time_jewellery_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
