# Generated by Django 4.2.2 on 2023-11-12 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_vegetable_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(default='None', upload_to='textile')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(default=None, max_length=50)),
                ('size', models.CharField(max_length=2)),
                ('size1', models.CharField(max_length=2)),
                ('size2', models.CharField(max_length=2)),
                ('size3', models.CharField(max_length=2)),
                ('mainprice', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('realprice', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
