# Generated by Django 4.2.2 on 2023-11-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_other'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photo',
            new_name='homephoto',
        ),
    ]
